name = "post_data"
method = "post"
[headers]
Content-Type="application/json"

[body]
content='''
[{
    "data":"{{.envVar}}"
}]
'''

[response]
template='''
[{
    "prop1":"@prop1",
    "prop2":"@prop2"
}]
'''

[output]
stdout='''
    {{.request_status}}   {{.responde[0]["@prop1"]}}
'''